apiVersion: skaffold/v1beta17
kind: Config
build:
  artifacts:
  - image: nyomio-demo-ui-skaffold
    docker:
      dockerfile: skaffold/Dockerfile
    sync:
      infer:
        - '**/*'
  local:
    useDockerCLI: true
    useBuildkit: true
    push: false
deploy:
  kubectl:
    manifests:
      - skaffold/k8s*.yaml
